Module(
    filename='/workspaces/spy/p.spy',
    docstring=None,
    decls=[
        Import(ref=<ImportRef math.sin>, asname='sin'),
        Import(ref=<ImportRef math.cos>, asname='cos'),
        Import(ref=<ImportRef math.sqrt>, asname='sqrt'),
        GlobalVarDef(
            vardef=VarDef(
                kind=None,
                name=StrConst(value='POINTS'),
                type=Auto(),
                value=Constant(value=100),
            ),
        ),
        GlobalClassDef(
            classdef=ClassDef(
                name='Point',
                kind='struct',
                docstring=None,
                fields=[
                    VarDef(
                        kind=None,
                        name=StrConst(value='x'),
                        type=Name(id='f64'),
                        value=None,
                    ),
                    VarDef(
                        kind=None,
                        name=StrConst(value='y'),
                        type=Name(id='f64'),
                        value=None,
                    ),
                    VarDef(
                        kind=None,
                        name=StrConst(value='z'),
                        type=Name(id='f64'),
                        value=None,
                    ),
                ],
                body=[
                    FuncDef(
                        color='red',
                        kind='plain',
                        name='__new__',
                        args=[
                            FuncArg(
                                name='i',
                                type=Name(id='i32'),
                                kind='simple',
                            ),
                        ],
                        return_type=Name(id='Point'),
                        docstring=None,
                        body=[
                            VarDef(
                                kind=None,
                                name=StrConst(value='_x'),
                                type=Name(id='f64'),
                                value=Call(
                                    func=Name(id='sin'),
                                    args=[
                                        Name(id='i'),
                                    ],
                                ),
                            ),
                            VarDef(
                                kind=None,
                                name=StrConst(value='_y'),
                                type=Name(id='f64'),
                                value=BinOp(
                                    op='*',
                                    left=Call(
                                        func=Name(id='cos'),
                                        args=[
                                            Name(id='i'),
                                        ],
                                    ),
                                    right=Constant(value=3),
                                ),
                            ),
                            VarDef(
                                kind=None,
                                name=StrConst(value='_z'),
                                type=Name(id='f64'),
                                value=BinOp(
                                    op='/',
                                    left=BinOp(
                                        op='*',
                                        left=Name(id='x'),
                                        right=Name(id='x'),
                                    ),
                                    right=Constant(value=2),
                                ),
                            ),
                            Return(
                                value=CallMethod(
                                    target=Name(id='Point'),
                                    method=StrConst(value='__make__'),
                                    args=[
                                        Name(id='_x'),
                                        Name(id='_y'),
                                        Name(id='_z'),
                                    ],
                                ),
                            ),
                        ],
                        decorators=[],
                        symtable=<SymTable 'p::Point::__new__' (red, function)>,
                    ),
                    FuncDef(
                        color='red',
                        kind='plain',
                        name='__repr__',
                        args=[
                            FuncArg(
                                name='self',
                                type=Auto(),
                                kind='simple',
                            ),
                        ],
                        return_type=Name(id='str'),
                        docstring=None,
                        body=[
                            Return(
                                value=BinOp(
                                    op='%',
                                    left=StrConst(value='<Point: x=%s, y=%s, z=%s>'),
                                    right=Tuple(
                                        items=[
                                            GetAttr(
                                                value=Name(id='self'),
                                                attr=StrConst(value='x'),
                                            ),
                                            GetAttr(
                                                value=Name(id='self'),
                                                attr=StrConst(value='y'),
                                            ),
                                            GetAttr(
                                                value=Name(id='self'),
                                                attr=StrConst(value='z'),
                                            ),
                                        ],
                                    ),
                                ),
                            ),
                        ],
                        decorators=[],
                        symtable=<SymTable 'p::Point::__repr__' (red, function)>,
                    ),
                    FuncDef(
                        color='red',
                        kind='plain',
                        name='normalize',
                        args=[
                            FuncArg(
                                name='self',
                                type=Auto(),
                                kind='simple',
                            ),
                        ],
                        return_type=Constant(value=None),
                        docstring=None,
                        body=[
                            Assign(
                                target=StrConst(value='_x'),
                                value=GetAttr(
                                    value=Name(id='self'),
                                    attr=StrConst(value='x'),
                                ),
                            ),
                            Assign(
                                target=StrConst(value='_y'),
                                value=GetAttr(
                                    value=Name(id='self'),
                                    attr=StrConst(value='y'),
                                ),
                            ),
                            Assign(
                                target=StrConst(value='_z'),
                                value=GetAttr(
                                    value=Name(id='self'),
                                    attr=StrConst(value='z'),
                                ),
                            ),
                            Assign(
                                target=StrConst(value='norm'),
                                value=Call(
                                    func=Name(id='sqrt'),
                                    args=[
                                        BinOp(
                                            op='+',
                                            left=BinOp(
                                                op='+',
                                                left=BinOp(
                                                    op='*',
                                                    left=Name(id='_x'),
                                                    right=Name(id='_x'),
                                                ),
                                                right=BinOp(
                                                    op='*',
                                                    left=Name(id='_y'),
                                                    right=Name(id='_y'),
                                                ),
                                            ),
                                            right=BinOp(
                                                op='*',
                                                left=Name(id='_z'),
                                                right=Name(id='_z'),
                                            ),
                                        ),
                                    ],
                                ),
                            ),
                            SetAttr(
                                target=Name(id='self'),
                                attr=StrConst(value='x'),
                                value=BinOp(
                                    op='/',
                                    left=GetAttr(
                                        value=Name(id='self'),
                                        attr=StrConst(value='x'),
                                    ),
                                    right=Name(id='norm'),
                                ),
                            ),
                            SetAttr(
                                target=Name(id='self'),
                                attr=StrConst(value='y'),
                                value=BinOp(
                                    op='/',
                                    left=GetAttr(
                                        value=Name(id='self'),
                                        attr=StrConst(value='y'),
                                    ),
                                    right=Name(id='norm'),
                                ),
                            ),
                            SetAttr(
                                target=Name(id='self'),
                                attr=StrConst(value='z'),
                                value=BinOp(
                                    op='/',
                                    left=GetAttr(
                                        value=Name(id='self'),
                                        attr=StrConst(value='z'),
                                    ),
                                    right=Name(id='norm'),
                                ),
                            ),
                        ],
                        decorators=[],
                        symtable=<SymTable 'p::Point::normalize' (red, function)>,
                    ),
                    FuncDef(
                        color='red',
                        kind='plain',
                        name='maximize',
                        args=[
                            FuncArg(
                                name='self',
                                type=Auto(),
                                kind='simple',
                            ),
                            FuncArg(
                                name='other',
                                type=Name(id='Point'),
                                kind='simple',
                            ),
                        ],
                        return_type=Name(id='Point'),
                        docstring=None,
                        body=[
                            If(
                                test=CmpOp(
                                    op='>',
                                    left=GetAttr(
                                        value=Name(id='self'),
                                        attr=StrConst(value='x'),
                                    ),
                                    right=GetAttr(
                                        value=Name(id='other'),
                                        attr=StrConst(value='x'),
                                    ),
                                ),
                                then_body=[
                                    SetAttr(
                                        target=Name(id='self'),
                                        attr=StrConst(value='x'),
                                        value=GetAttr(
                                            value=Name(id='self'),
                                            attr=StrConst(value='x'),
                                        ),
                                    ),
                                ],
                                else_body=[
                                    StmtExpr(
                                        value=GetAttr(
                                            value=Name(id='other'),
                                            attr=StrConst(value='x'),
                                        ),
                                    ),
                                ],
                            ),
                            If(
                                test=CmpOp(
                                    op='>',
                                    left=GetAttr(
                                        value=Name(id='self'),
                                        attr=StrConst(value='y'),
                                    ),
                                    right=GetAttr(
                                        value=Name(id='other'),
                                        attr=StrConst(value='y'),
                                    ),
                                ),
                                then_body=[
                                    SetAttr(
                                        target=Name(id='self'),
                                        attr=StrConst(value='y'),
                                        value=GetAttr(
                                            value=Name(id='self'),
                                            attr=StrConst(value='y'),
                                        ),
                                    ),
                                ],
                                else_body=[
                                    StmtExpr(
                                        value=GetAttr(
                                            value=Name(id='other'),
                                            attr=StrConst(value='y'),
                                        ),
                                    ),
                                ],
                            ),
                            If(
                                test=CmpOp(
                                    op='>',
                                    left=GetAttr(
                                        value=Name(id='self'),
                                        attr=StrConst(value='z'),
                                    ),
                                    right=GetAttr(
                                        value=Name(id='other'),
                                        attr=StrConst(value='z'),
                                    ),
                                ),
                                then_body=[
                                    SetAttr(
                                        target=Name(id='self'),
                                        attr=StrConst(value='z'),
                                        value=GetAttr(
                                            value=Name(id='self'),
                                            attr=StrConst(value='z'),
                                        ),
                                    ),
                                ],
                                else_body=[
                                    StmtExpr(
                                        value=GetAttr(
                                            value=Name(id='other'),
                                            attr=StrConst(value='z'),
                                        ),
                                    ),
                                ],
                            ),
                            Return(
                                value=Name(id='self'),
                            ),
                        ],
                        decorators=[],
                        symtable=<SymTable 'p::Point::maximize' (red, function)>,
                    ),
                ],
                symtable=<SymTable 'p::Point' (blue, class)>,
            ),
        ),
        GlobalFuncDef(
            funcdef=FuncDef(
                color='red',
                kind='plain',
                name='maximize',
                args=[
                    FuncArg(
                        name='points',
                        type=GetItem(
                            value=Name(id='list'),
                            args=[
                                Name(id='Point'),
                            ],
                        ),
                        kind='simple',
                    ),
                ],
                return_type=Name(id='Point'),
                docstring=None,
                body=[
                    Assign(
                        target=StrConst(value='next'),
                        value=GetItem(
                            value=Name(id='points'),
                            args=[
                                Constant(value=0),
                            ],
                        ),
                    ),
                    For(
                        seq=0,
                        target=StrConst(value='p'),
                        iter=GetItem(
                            value=Name(id='points'),
                            args=[
                                Slice(
                                    start=Constant(value=1),
                                    stop=None,
                                    step=None,
                                ),
                            ],
                        ),
                        body=[
                            Assign(
                                target=StrConst(value='next'),
                                value=CallMethod(
                                    target=Name(id='next'),
                                    method=StrConst(value='maximize'),
                                    args=[
                                        Name(id='p'),
                                    ],
                                ),
                            ),
                        ],
                    ),
                    Return(
                        value=Name(id='next'),
                    ),
                ],
                decorators=[],
                symtable=<SymTable 'p::maximize' (red, function)>,
            ),
        ),
        GlobalFuncDef(
            funcdef=FuncDef(
                color='red',
                kind='plain',
                name='benchmark',
                args=[
                    FuncArg(
                        name='n',
                        type=Name(id='i32'),
                        kind='simple',
                    ),
                ],
                return_type=Name(id='Point'),
                docstring=None,
                body=[
                    VarDef(
                        kind=None,
                        name=StrConst(value='points'),
                        type=GetItem(
                            value=Name(id='list'),
                            args=[
                                Name(id='f64'),
                            ],
                        ),
                        value=List(
                            items=[],
                        ),
                    ),
                    For(
                        seq=0,
                        target=StrConst(value='i'),
                        iter=Call(
                            func=Name(id='range'),
                            args=[
                                Name(id='n'),
                            ],
                        ),
                        body=[
                            StmtExpr(
                                value=CallMethod(
                                    target=Name(id='points'),
                                    method=StrConst(value='append'),
                                    args=[
                                        Call(
                                            func=Name(id='Point'),
                                            args=[
                                                Name(id='i'),
                                            ],
                                        ),
                                    ],
                                ),
                            ),
                            If(
                                test=UnaryOp(
                                    op='not',
                                    value=BinOp(
                                        op='%',
                                        left=Name(id='i'),
                                        right=Constant(value=100),
                                    ),
                                ),
                                then_body=[
                                    StmtExpr(
                                        value=Call(
                                            func=Name(id='print'),
                                            args=[
                                                Name(id='i'),
                                            ],
                                        ),
                                    ),
                                ],
                                else_body=[],
                            ),
                        ],
                    ),
                    For(
                        seq=1,
                        target=StrConst(value='p'),
                        iter=Name(id='points'),
                        body=[
                            StmtExpr(
                                value=CallMethod(
                                    target=Name(id='p'),
                                    method=StrConst(value='normalize'),
                                    args=[],
                                ),
                            ),
                        ],
                    ),
                    Return(
                        value=Call(
                            func=Name(id='maximize'),
                            args=[
                                Name(id='points'),
                            ],
                        ),
                    ),
                ],
                decorators=[],
                symtable=<SymTable 'p::benchmark' (red, function)>,
            ),
        ),
        GlobalFuncDef(
            funcdef=FuncDef(
                color='red',
                kind='plain',
                name='main',
                args=[],
                return_type=Constant(value=None),
                docstring=None,
                body=[
                    StmtExpr(
                        value=Call(
                            func=Name(id='print'),
                            args=[
                                Call(
                                    func=Name(id='benchmark'),
                                    args=[
                                        Name(id='POINTS'),
                                    ],
                                ),
                            ],
                        ),
                    ),
                ],
                decorators=[],
                symtable=<SymTable 'p::main' (red, function)>,
            ),
        ),
    ],
    symtable=<SymTable 'p' (blue, module)>,
)
